from qiskit import *
import numpy as np
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit, transpile
from qiskit_aer import AerSimulator
from qiskit_aer.noise import (
    NoiseModel,
    QuantumError,
    ReadoutError,
    pauli_error,
    depolarizing_error,
    thermal_relaxation_error,
)
from qiskit.circuit import QuantumCircuit, Qubit, Clbit
from PostProcessing import *
from Oracles import *
from qiskit.circuit.library import UGate
import math
import sympy as sp


# ---------------------------------------------------------
# Analytical final sigmas
# ---------------------------------------------------------

def calculate_sigmas_analytical(arr, k):
    """
    Calculate final local Gaussian widths analytically.

    Output
    ------
    q_params[i] = (sigma_theta_i, sigma_phi_i)

    Model
    -----
    - Fresh rotational errors are inserted after each single-qubit gate.
    - Each fresh error adds variance k^2 to theta and phi.
    - H swaps theta-like and phi-like errors.
    - X, Y, Z, S add fresh local noise but do not change local widths
      in this reduced approximation.
    - CX does not add fresh noise.
    - SWAP exchanges the local widths between the two qubits.

    This is a local independent approximation. It does not keep
    two-qubit error strings generated by CX propagation.
    """

    n_qubits = arr[0]
    depth = len(arr) - 1

    # Store variances first, not sigmas.
    var_params = [(sp.Integer(0), sp.Integer(0)) for _ in range(n_qubits)]

    def add_gate_noise(pair):
        vt, vp = pair
        return (vt + k**2, vp + k**2)

    def hadamard_pair(pair):
        vt, vp = pair
        return (vp, vt)

    for i in range(1, depth + 1):
        gate_type, payload = arr[i]

        if gate_type == "h":
            qubit = payload

            # H maps X-like errors to Z-like errors and conversely.
            var_params[qubit] = hadamard_pair(var_params[qubit])

            # Fresh physical noise after H.
            var_params[qubit] = add_gate_noise(var_params[qubit])

        elif gate_type in ("x", "y", "z", "s"):
            qubit = payload

            # In this reduced local-width model these gates do not change
            # the theta/phi widths, but they do add fresh physical noise.
            var_params[qubit] = add_gate_noise(var_params[qubit])

        elif gate_type == "cx":
            # No fresh physical noise after CX in this model.
            # We also do not project two-qubit propagated errors back
            # into local widths.
            continue

        elif gate_type == "swap":
            q0, q1 = payload
            var_params[q0], var_params[q1] = var_params[q1], var_params[q0]
            
        elif gate_type == "barrier":
            # do nothing
            aa = 0

        else:
            raise ValueError(f"Unknown gate type '{gate_type}'")

    q_params = [
        (sp.sqrt(vt), sp.sqrt(vp))
        for vt, vp in var_params
    ]

    return q_params


# ---------------------------------------------------------
# Sampling and error gates
# ---------------------------------------------------------

def choose(kt, kp, loct=0.0, locp=0.0, wrap=True):
    """
    Sample one pair of angles.

    theta ~ N(loct, kt^2)
    phi   ~ N(locp, kp^2)

    kt and kp are standard deviations, not variances.
    """

    theta = np.random.normal(loc=loct, scale=kt)
    phi = np.random.normal(loc=locp, scale=kp)

    if wrap:
        theta = (theta + np.pi) % (2 * np.pi) - np.pi
        phi = (phi + np.pi) % (2 * np.pi) - np.pi

    return theta, phi


def r_error_gate(qc, theta, phi, qubit):
    """
    Continuous rotational error:

        Z Rx(2 theta) Rz(-2 phi) Z
    """

    qc.z(qubit)
    qc.rx(2 * theta, qubit)
    qc.rz(-2 * phi, qubit)
    qc.z(qubit)

    return qc


def insert_error(qc, qubit, theta, phi):
    """
    Insert one sampled continuous error on one qubit.
    """

    return r_error_gate(qc, theta, phi, qubit)

def insert_error11(qc,pos,k):
    for p in pos:
        theta = np.random.normal(loc=0.0, scale=k)
        phi = np.random.normal(loc=0.0, scale=k)
        qc = r_error_gate(qc, theta, phi, p)
    return qc

def sample_angles_from_sigmas(q_sigmas, k_symbol, sig):
    """
    Sample final independent angles from the analytical sigmas.

    q_sigmas[i] = (sigma_theta_i, sigma_phi_i)

    Returns
    -------
    sampled_angles[i] = (theta_i, phi_i)
    """

    sampled_angles = []

    for st_expr, sp_expr in q_sigmas:
        st = float(st_expr.subs(k_symbol, sig))
        sp_ = float(sp_expr.subs(k_symbol, sig))

        theta, phi = choose(st, sp_)
        sampled_angles.append((theta, phi))

    return sampled_angles


# ---------------------------------------------------------
# Circuit conversion
# ---------------------------------------------------------

def qubit_index(q, qc):
    return qc.qubits.index(q)


def circuit_to_array(qc):
    """
    Convert a Qiskit circuit into the list format used by the
    analytical approximation.

    The output has the form:

        [[gate_name, payload], ...]

    CZ is decomposed as:

        CZ(i,j) = H_j CX(i,j) H_j
    """

    flat = transpile(
        qc,
        basis_gates=["h", "x", "y", "z", "cx", "cz", "swap"],
        optimization_level=0,
    )

    ops = []

    for inst in flat.data:
        name = inst.operation.name.lower()
        qubits = [flat.qubits.index(q) for q in inst.qubits]

        if name == "cz":
            i, j = qubits
            ops.append(["h", j])
            ops.append(["cx", [i, j]])
            ops.append(["h", j])

        elif len(qubits) == 1:
            ops.append([name, qubits[0]])

        else:
            ops.append([name, qubits])

    return ops


# ---------------------------------------------------------
# Encoded circuit
# ---------------------------------------------------------

def Circuit(n_h, correction):
    """
    Build the encoded circuit used to calculate the analytical final sigmas.

    If correction=False:
        use 5 physical qubits.

    If correction=True:
        use 5 data qubits + 4 ancilla qubits.
    """

    nbq = 4 if correction else 0

    qq = QuantumRegister(5 + nbq)
    cc = ClassicalRegister(5 + nbq)
    qc = QuantumCircuit(qq, cc)

    qc.compose(encode(), range(5), inplace=True)

    for _ in range(n_h):
        qc.append(Logical_Hadamard(), range(5))

    if correction:
        qc.h([2,3])
        #qc.compose(detection(), range(9), inplace=True)
        qc.h(range(5,9))
        qc.h(range(5,9))

    return qc

cs1 = QuantumCircuit(5)
cs1.cx(4,0)
cs1.cz(4,1)
cs1.cz(4,2)
cs1.cx(4,3)
cs3 = QuantumCircuit(5)
cs3.cz(4,0)
cs3.cz(4,1)
cs3.cx(4,2)
cs3.cx(4,3)
cs4 = QuantumCircuit(5)
cs4.cz(4,0)
cs4.cx(4,1)
cs4.cx(4,2)
cs4.cz(4,3)
def detection_ed(k):
    """Noisy Error detection circuit of [[5,1,3]]."""
    qc = QuantumCircuit(9,name='$Error$ $Detection$')
    qc.barrier()
    qc.h(range(5,9))
    qc.barrier()
    qc.compose(cs1,[4,3,2,1,5],inplace=True)
    qc = insert_error11(qc,[1,3],k)
    qc = insert_error11(qc,[2],np.sqrt(2)*k)
    qc.barrier()
    qc.compose(cs1,[3,2,1,0,6],inplace=True)
    qc = insert_error11(qc,[0,2],k)
    qc = insert_error11(qc,[1],np.sqrt(2)*k)
    qc.barrier()
    qc.compose(cs3,[0,1,2,4,7],inplace=True)
    qc = insert_error11(qc,[1,4],k)
    qc = insert_error11(qc,[0],np.sqrt(2)*k)
    qc.barrier()
    qc.compose(cs4,[4,3,1,0,8],inplace=True)
    qc = insert_error11(qc,[0,4],k)
    qc.barrier()
    qc.h(range(5,9))
    qc.barrier()
    return qc

def single_encoded_qubit(shots, times, correction, sampled_angles,k):
    """
    Run the approximation circuit.

    The ideal logical Hadamards are not explicitly applied here.
    This is consistent when n_h is even, because H_L^(even) = I,
    and the effect of the intermediate noisy Hadamards is already
    included in sampled_angles through calculate_sigmas_analytical.

    For odd n_h, this function would need to include one final
    Logical_Hadamard before the final errors or before measurement,
    depending on the convention you want.
    """

    nbq = 4 if correction else 0
    n_qubits = 5 + nbq

    if len(sampled_angles) != n_qubits:
        raise ValueError(
            f"sampled_angles must contain {n_qubits} pairs, "
            f"but got {len(sampled_angles)}"
        )

    qq = QuantumRegister(n_qubits)
    cc = ClassicalRegister(n_qubits)
    qc = QuantumCircuit(qq, cc)

    qc.compose(encode(), range(5), inplace=True)

    # Insert one final effective error on each qubit.
    for q3 in range(n_qubits-nbq):
        theta, phi = sampled_angles[q3]
        qc = insert_error(qc, qq[q3], theta, phi)

    if correction:
        qc.compose(detection_ed(k), range(9), inplace=True)
        for q3 in range(n_qubits-nbq,n_qubits):
            theta, phi = sampled_angles[q3]
            qc = insert_error(qc, qq[q3], theta, phi)

        qc = decode_correction(qc, qq, [cc[5], cc[6], cc[7], cc[8]])

    for i in range(5):
        qc.measure(qq[i], cc[i])

    return runcircxtimes(qc, shots, times)


# ---------------------------------------------------------
# Main scan over noise strengths
# ---------------------------------------------------------

def Run1Qbt_AllNoise(a, b, num, shots, times, n_h, correction):
    """
    Run the approximation model for a range of noise strengths.

    The old SVD sampling has been removed. Now we:

        1. Build the encoded circuit.
        2. Convert it to a gate list.
        3. Calculate final qubit-dependent sigmas analytically.
        4. For each sigma, sample one final error per qubit.
        5. Run the approximation circuit.
    """

    n_qubits = 9 if correction else 5

    p_errors = (1 / 3) * np.logspace(a, b, num=num)

    arr = [n_qubits] + circuit_to_array(Circuit(n_h, correction))

    k = sp.symbols("k", positive=True, real=True)

    q_sigmas = calculate_sigmas_analytical(arr, k)

    results = []

    for sig in p_errors:
        sampled_angles = sample_angles_from_sigmas(
            q_sigmas=q_sigmas,
            k_symbol=k,
            sig=sig,
        )

        result = single_encoded_qubit(
            shots=shots,
            times=times,
            correction=correction,
            sampled_angles=sampled_angles,
            k=sig
        )

        results.append(result)

    return results


# ---------------------------------------------------------
# Saving
# ---------------------------------------------------------

def save_table(table, filename, shots):
    """
    Save raw output table in append mode.
    """

    with open(filename, "a") as file:
        file.write(f"Shots = {shots}\n")

        for row in table:
            if isinstance(row, (list, tuple, np.ndarray)):
                file.write(" ".join(map(str, row)) + "\n")
            else:
                file.write(str(row) + "\n")

        file.write("\n")


# ---------------------------------------------------------
# Run
# ---------------------------------------------------------

shots = 1000
times = 10
n_h = 10
correction = True
if correction:
    ec = "1"
else:
    ec = "0"

table = Run1Qbt_AllNoise(
    a=-6,
    b=-1,
    num=20,
    shots=shots,
    times=times,
    n_h=n_h,
    correction=correction,
)

save_table(
    table,
    filename=f"Enc513Approx-m={str(n_h)}-ec={ec}.txt",
    shots=shots,
)
